<?php
/**
 * fix_identity — Roundcube plugin for mailproxy.
 *
 * On every login, resolves the IMAP login username to a canonical email
 * address by looking it up in /var/credentials/alias_map (generated by
 * the fetcher service).
 *
 * alias_map format (two whitespace-separated columns):
 *   imap-login   canonical@email.address
 *
 * Lines starting with '#' and blank lines are ignored.
 * If the login is not in the map, nothing is changed.
 */
class fix_identity extends rcube_plugin
{
    const MAP_FILE = '/var/credentials/alias_map';

    public function init()
    {
        $this->add_hook('login_after', [$this, 'fix_default_identity']);
    }

    public function fix_default_identity($args)
    {
        $rcube = rcube::get_instance();
        $user  = $rcube->user;

        if (!$user || !$user->ID) {
            return $args;
        }

        $canonical = $this->resolve($user->get_username());
        if (!$canonical) {
            return $args;
        }

        $identities = $user->list_identities();

        // Fix the standard (default) identity if its email is wrong.
        foreach ($identities as $id) {
            if (!empty($id['standard']) && $id['email'] !== $canonical) {
                $user->update_identity($id['identity_id'], ['email' => $canonical]);
                return $args;
            }
        }

        // No identities at all — create a default one.
        if (empty($identities)) {
            $user->insert_identity(['email' => $canonical, 'name' => '', 'standard' => 1]);
        }

        return $args;
    }

    private function resolve($login)
    {
        if (!is_readable(self::MAP_FILE)) {
            return null;
        }

        foreach (file(self::MAP_FILE, FILE_IGNORE_NEW_LINES | FILE_SKIP_EMPTY_LINES) as $line) {
            if ($line === '' || $line[0] === '#') {
                continue;
            }
            $parts = preg_split('/\s+/', trim($line), 2);
            if (count($parts) === 2 && $parts[0] === $login) {
                return $parts[1];
            }
        }

        return null;
    }
}
